### ISSUE TITLE
error

### ISSUE THREAD

**Issue by seltoxx** [chaarlottte/discord-generator#6]
self.logger.warn(title="ERROR", data=f"Captcha error: {self.captchaSolution.split('.')[0]}")
                                                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'creator' object has no attribute 'captchaSolution'

**Comment by laika-cosmonaut** [comment]
You likely modified code that you shouldn’t have. This should, at the very least, be `None`. Your captcha API key may also be invalid.
