### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by karimHI** [chaarlottte/discord-generator#7]
`python main.py
Traceback (most recent call last):
  File "/root/discord-generator/main.py", line 114, in <module>
    main()
  File "/root/discord-generator/main.py", line 105, in main
    logger = Logger(True, defaultPrefix=f"<TIME> GENERATOR")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Logger.__init__() got an unexpected keyword argument 'defaultPrefix'
`

**Comment by laika-cosmonaut** [comment]
Fixed in b293100

**Comment by laika-cosmonaut** [comment]
Okay, *actually* fixed in fc8344f. I think.
